/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCafeSlugRouteImport } from './routes/_authenticated/cafe.$slug'
import { Route as AuthenticatedCafeSlugStaffRouteImport } from './routes/_authenticated/cafe.$slug.staff'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCafeSlugRoute = AuthenticatedCafeSlugRouteImport.update({
  id: '/cafe/$slug',
  path: '/cafe/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCafeSlugStaffRoute =
  AuthenticatedCafeSlugStaffRouteImport.update({
    id: '/staff',
    path: '/staff',
    getParentRoute: () => AuthenticatedCafeSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/cafe/$slug': typeof AuthenticatedCafeSlugRouteWithChildren
  '/cafe/$slug/staff': typeof AuthenticatedCafeSlugStaffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/cafe/$slug': typeof AuthenticatedCafeSlugRouteWithChildren
  '/cafe/$slug/staff': typeof AuthenticatedCafeSlugStaffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/cafe/$slug': typeof AuthenticatedCafeSlugRouteWithChildren
  '/_authenticated/cafe/$slug/staff': typeof AuthenticatedCafeSlugStaffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/setup'
    | '/admin'
    | '/portal'
    | '/cafe/$slug'
    | '/cafe/$slug/staff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/setup'
    | '/admin'
    | '/portal'
    | '/cafe/$slug'
    | '/cafe/$slug/staff'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/setup'
    | '/_authenticated/admin'
    | '/_authenticated/portal'
    | '/_authenticated/cafe/$slug'
    | '/_authenticated/cafe/$slug/staff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cafe/$slug': {
      id: '/_authenticated/cafe/$slug'
      path: '/cafe/$slug'
      fullPath: '/cafe/$slug'
      preLoaderRoute: typeof AuthenticatedCafeSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cafe/$slug/staff': {
      id: '/_authenticated/cafe/$slug/staff'
      path: '/staff'
      fullPath: '/cafe/$slug/staff'
      preLoaderRoute: typeof AuthenticatedCafeSlugStaffRouteImport
      parentRoute: typeof AuthenticatedCafeSlugRoute
    }
  }
}

interface AuthenticatedCafeSlugRouteChildren {
  AuthenticatedCafeSlugStaffRoute: typeof AuthenticatedCafeSlugStaffRoute
}

const AuthenticatedCafeSlugRouteChildren: AuthenticatedCafeSlugRouteChildren = {
  AuthenticatedCafeSlugStaffRoute: AuthenticatedCafeSlugStaffRoute,
}

const AuthenticatedCafeSlugRouteWithChildren =
  AuthenticatedCafeSlugRoute._addFileChildren(
    AuthenticatedCafeSlugRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedCafeSlugRoute: typeof AuthenticatedCafeSlugRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedCafeSlugRoute: AuthenticatedCafeSlugRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
