/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RedirectingRouteImport } from './routes/redirecting'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedOwnerRouteImport } from './routes/_authenticated/owner'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedOwnerHelpRouteImport } from './routes/_authenticated/owner_.help'
import { Route as AuthenticatedCafeSlugRouteImport } from './routes/_authenticated/cafe.$slug'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminRevenueRouteImport } from './routes/_authenticated/admin.revenue'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin.leads'
import { Route as AuthenticatedAdminHealthRouteImport } from './routes/_authenticated/admin.health'
import { Route as AuthenticatedAdminConfigRouteImport } from './routes/_authenticated/admin.config'
import { Route as AuthenticatedAdminCafesRouteImport } from './routes/_authenticated/admin.cafes'
import { Route as AuthenticatedAdminBackupsRouteImport } from './routes/_authenticated/admin.backups'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminApiKeysRouteImport } from './routes/_authenticated/admin.api-keys'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin.announcements'
import { Route as AuthenticatedCafeSlugIndexRouteImport } from './routes/_authenticated/cafe.$slug.index'
import { Route as CSlugTournamentsIdRouteImport } from './routes/c.$slug.tournaments.$id'
import { Route as AuthenticatedCafeSlugWalletRouteImport } from './routes/_authenticated/cafe.$slug.wallet'
import { Route as AuthenticatedCafeSlugTournamentsRouteImport } from './routes/_authenticated/cafe.$slug.tournaments'
import { Route as AuthenticatedCafeSlugSupportRouteImport } from './routes/_authenticated/cafe.$slug.support'
import { Route as AuthenticatedCafeSlugStaffRouteImport } from './routes/_authenticated/cafe.$slug.staff'
import { Route as AuthenticatedCafeSlugReportsRouteImport } from './routes/_authenticated/cafe.$slug.reports'
import { Route as AuthenticatedCafeSlugPosRouteImport } from './routes/_authenticated/cafe.$slug.pos'
import { Route as AuthenticatedCafeSlugPageRouteImport } from './routes/_authenticated/cafe.$slug.page'
import { Route as AuthenticatedCafeSlugMenuRouteImport } from './routes/_authenticated/cafe.$slug.menu'
import { Route as AuthenticatedCafeSlugMembershipsRouteImport } from './routes/_authenticated/cafe.$slug.memberships'
import { Route as AuthenticatedCafeSlugLedgerRouteImport } from './routes/_authenticated/cafe.$slug.ledger'
import { Route as AuthenticatedCafeSlugFloorRouteImport } from './routes/_authenticated/cafe.$slug.floor'
import { Route as AuthenticatedCafeSlugDevicesRouteImport } from './routes/_authenticated/cafe.$slug.devices'
import { Route as AuthenticatedCafeSlugCustomersRouteImport } from './routes/_authenticated/cafe.$slug.customers'
import { Route as AuthenticatedCafeSlugBookingsRouteImport } from './routes/_authenticated/cafe.$slug.bookings'
import { Route as AuthenticatedCafeSlugAuditRouteImport } from './routes/_authenticated/cafe.$slug.audit'
import { Route as AuthenticatedCafeSlugAnalyticsRouteImport } from './routes/_authenticated/cafe.$slug.analytics'
import { Route as AuthenticatedCafeSlugTournamentsIdRouteImport } from './routes/_authenticated/cafe.$slug.tournaments.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectingRoute = RedirectingRouteImport.update({
  id: '/redirecting',
  path: '/redirecting',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerRoute = AuthenticatedOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedOwnerHelpRoute = AuthenticatedOwnerHelpRouteImport.update({
  id: '/owner_/help',
  path: '/owner/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCafeSlugRoute = AuthenticatedCafeSlugRouteImport.update({
  id: '/cafe/$slug',
  path: '/cafe/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRevenueRoute =
  AuthenticatedAdminRevenueRouteImport.update({
    id: '/revenue',
    path: '/revenue',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminHealthRoute =
  AuthenticatedAdminHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfigRoute =
  AuthenticatedAdminConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCafesRoute = AuthenticatedAdminCafesRouteImport.update({
  id: '/cafes',
  path: '/cafes',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBackupsRoute =
  AuthenticatedAdminBackupsRouteImport.update({
    id: '/backups',
    path: '/backups',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminApiKeysRoute =
  AuthenticatedAdminApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedCafeSlugIndexRoute =
  AuthenticatedCafeSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCafeSlugRoute,
  } as any)
const CSlugTournamentsIdRoute = CSlugTournamentsIdRouteImport.update({
  id: '/tournaments/$id',
  path: '/tournaments/$id',
  getParentRoute: () => CSlugRoute,
} as any)
const AuthenticatedCafeSlugWalletRoute =
  AuthenticatedCafeSlugWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AuthenticatedCafeSlugRoute,
  } as any)
const AuthenticatedCafeSlugTournamentsRoute =
  AuthenticatedCafeSlugTournamentsRouteImport.update({
    id: '/tournaments',
    path: '/tournaments',
    getParentRoute: () => AuthenticatedCafeSlugRoute,
  } as any)
const AuthenticatedCafeSlugSupportRoute =
  AuthenticatedCafeSlugSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedCafeSlugRoute,
  } as any)
const AuthenticatedCafeSlugStaffRoute =
  AuthenticatedCafeSlugStaffRouteImport.update({
    id: '/staff',
    path: '/staff',
    getParentRoute: () => AuthenticatedCafeSlugRoute,
  } as any)
const AuthenticatedCafeSlugReportsRoute =
  AuthenticatedCafeSlugReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedCafeSlugRoute,
  } as any)
const AuthenticatedCafeSlugPosRoute =
  AuthenticatedCafeSlugPosRouteImport.update({
    id: '/pos',
    path: '/pos',
    getParentRoute: () => AuthenticatedCafeSlugRoute,
  } as any)
const AuthenticatedCafeSlugPageRoute =
  AuthenticatedCafeSlugPageRouteImport.update({
    id: '/page',
    path: '/page',
    getParentRoute: () => AuthenticatedCafeSlugRoute,
  } as any)
const AuthenticatedCafeSlugMenuRoute =
  AuthenticatedCafeSlugMenuRouteImport.update({
    id: '/menu',
    path: '/menu',
    getParentRoute: () => AuthenticatedCafeSlugRoute,
  } as any)
const AuthenticatedCafeSlugMembershipsRoute =
  AuthenticatedCafeSlugMembershipsRouteImport.update({
    id: '/memberships',
    path: '/memberships',
    getParentRoute: () => AuthenticatedCafeSlugRoute,
  } as any)
const AuthenticatedCafeSlugLedgerRoute =
  AuthenticatedCafeSlugLedgerRouteImport.update({
    id: '/ledger',
    path: '/ledger',
    getParentRoute: () => AuthenticatedCafeSlugRoute,
  } as any)
const AuthenticatedCafeSlugFloorRoute =
  AuthenticatedCafeSlugFloorRouteImport.update({
    id: '/floor',
    path: '/floor',
    getParentRoute: () => AuthenticatedCafeSlugRoute,
  } as any)
const AuthenticatedCafeSlugDevicesRoute =
  AuthenticatedCafeSlugDevicesRouteImport.update({
    id: '/devices',
    path: '/devices',
    getParentRoute: () => AuthenticatedCafeSlugRoute,
  } as any)
const AuthenticatedCafeSlugCustomersRoute =
  AuthenticatedCafeSlugCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedCafeSlugRoute,
  } as any)
const AuthenticatedCafeSlugBookingsRoute =
  AuthenticatedCafeSlugBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedCafeSlugRoute,
  } as any)
const AuthenticatedCafeSlugAuditRoute =
  AuthenticatedCafeSlugAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedCafeSlugRoute,
  } as any)
const AuthenticatedCafeSlugAnalyticsRoute =
  AuthenticatedCafeSlugAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedCafeSlugRoute,
  } as any)
const AuthenticatedCafeSlugTournamentsIdRoute =
  AuthenticatedCafeSlugTournamentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCafeSlugTournamentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/redirecting': typeof RedirectingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/owner': typeof AuthenticatedOwnerRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/c/$slug': typeof CSlugRouteWithChildren
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/backups': typeof AuthenticatedAdminBackupsRoute
  '/admin/cafes': typeof AuthenticatedAdminCafesRoute
  '/admin/config': typeof AuthenticatedAdminConfigRoute
  '/admin/health': typeof AuthenticatedAdminHealthRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/revenue': typeof AuthenticatedAdminRevenueRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/cafe/$slug': typeof AuthenticatedCafeSlugRouteWithChildren
  '/owner/help': typeof AuthenticatedOwnerHelpRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/cafe/$slug/analytics': typeof AuthenticatedCafeSlugAnalyticsRoute
  '/cafe/$slug/audit': typeof AuthenticatedCafeSlugAuditRoute
  '/cafe/$slug/bookings': typeof AuthenticatedCafeSlugBookingsRoute
  '/cafe/$slug/customers': typeof AuthenticatedCafeSlugCustomersRoute
  '/cafe/$slug/devices': typeof AuthenticatedCafeSlugDevicesRoute
  '/cafe/$slug/floor': typeof AuthenticatedCafeSlugFloorRoute
  '/cafe/$slug/ledger': typeof AuthenticatedCafeSlugLedgerRoute
  '/cafe/$slug/memberships': typeof AuthenticatedCafeSlugMembershipsRoute
  '/cafe/$slug/menu': typeof AuthenticatedCafeSlugMenuRoute
  '/cafe/$slug/page': typeof AuthenticatedCafeSlugPageRoute
  '/cafe/$slug/pos': typeof AuthenticatedCafeSlugPosRoute
  '/cafe/$slug/reports': typeof AuthenticatedCafeSlugReportsRoute
  '/cafe/$slug/staff': typeof AuthenticatedCafeSlugStaffRoute
  '/cafe/$slug/support': typeof AuthenticatedCafeSlugSupportRoute
  '/cafe/$slug/tournaments': typeof AuthenticatedCafeSlugTournamentsRouteWithChildren
  '/cafe/$slug/wallet': typeof AuthenticatedCafeSlugWalletRoute
  '/c/$slug/tournaments/$id': typeof CSlugTournamentsIdRoute
  '/cafe/$slug/': typeof AuthenticatedCafeSlugIndexRoute
  '/cafe/$slug/tournaments/$id': typeof AuthenticatedCafeSlugTournamentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/redirecting': typeof RedirectingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/owner': typeof AuthenticatedOwnerRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/c/$slug': typeof CSlugRouteWithChildren
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/backups': typeof AuthenticatedAdminBackupsRoute
  '/admin/cafes': typeof AuthenticatedAdminCafesRoute
  '/admin/config': typeof AuthenticatedAdminConfigRoute
  '/admin/health': typeof AuthenticatedAdminHealthRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/revenue': typeof AuthenticatedAdminRevenueRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/owner/help': typeof AuthenticatedOwnerHelpRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/cafe/$slug/analytics': typeof AuthenticatedCafeSlugAnalyticsRoute
  '/cafe/$slug/audit': typeof AuthenticatedCafeSlugAuditRoute
  '/cafe/$slug/bookings': typeof AuthenticatedCafeSlugBookingsRoute
  '/cafe/$slug/customers': typeof AuthenticatedCafeSlugCustomersRoute
  '/cafe/$slug/devices': typeof AuthenticatedCafeSlugDevicesRoute
  '/cafe/$slug/floor': typeof AuthenticatedCafeSlugFloorRoute
  '/cafe/$slug/ledger': typeof AuthenticatedCafeSlugLedgerRoute
  '/cafe/$slug/memberships': typeof AuthenticatedCafeSlugMembershipsRoute
  '/cafe/$slug/menu': typeof AuthenticatedCafeSlugMenuRoute
  '/cafe/$slug/page': typeof AuthenticatedCafeSlugPageRoute
  '/cafe/$slug/pos': typeof AuthenticatedCafeSlugPosRoute
  '/cafe/$slug/reports': typeof AuthenticatedCafeSlugReportsRoute
  '/cafe/$slug/staff': typeof AuthenticatedCafeSlugStaffRoute
  '/cafe/$slug/support': typeof AuthenticatedCafeSlugSupportRoute
  '/cafe/$slug/tournaments': typeof AuthenticatedCafeSlugTournamentsRouteWithChildren
  '/cafe/$slug/wallet': typeof AuthenticatedCafeSlugWalletRoute
  '/c/$slug/tournaments/$id': typeof CSlugTournamentsIdRoute
  '/cafe/$slug': typeof AuthenticatedCafeSlugIndexRoute
  '/cafe/$slug/tournaments/$id': typeof AuthenticatedCafeSlugTournamentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/redirecting': typeof RedirectingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/owner': typeof AuthenticatedOwnerRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/c/$slug': typeof CSlugRouteWithChildren
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/backups': typeof AuthenticatedAdminBackupsRoute
  '/_authenticated/admin/cafes': typeof AuthenticatedAdminCafesRoute
  '/_authenticated/admin/config': typeof AuthenticatedAdminConfigRoute
  '/_authenticated/admin/health': typeof AuthenticatedAdminHealthRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/revenue': typeof AuthenticatedAdminRevenueRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/cafe/$slug': typeof AuthenticatedCafeSlugRouteWithChildren
  '/_authenticated/owner_/help': typeof AuthenticatedOwnerHelpRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/cafe/$slug/analytics': typeof AuthenticatedCafeSlugAnalyticsRoute
  '/_authenticated/cafe/$slug/audit': typeof AuthenticatedCafeSlugAuditRoute
  '/_authenticated/cafe/$slug/bookings': typeof AuthenticatedCafeSlugBookingsRoute
  '/_authenticated/cafe/$slug/customers': typeof AuthenticatedCafeSlugCustomersRoute
  '/_authenticated/cafe/$slug/devices': typeof AuthenticatedCafeSlugDevicesRoute
  '/_authenticated/cafe/$slug/floor': typeof AuthenticatedCafeSlugFloorRoute
  '/_authenticated/cafe/$slug/ledger': typeof AuthenticatedCafeSlugLedgerRoute
  '/_authenticated/cafe/$slug/memberships': typeof AuthenticatedCafeSlugMembershipsRoute
  '/_authenticated/cafe/$slug/menu': typeof AuthenticatedCafeSlugMenuRoute
  '/_authenticated/cafe/$slug/page': typeof AuthenticatedCafeSlugPageRoute
  '/_authenticated/cafe/$slug/pos': typeof AuthenticatedCafeSlugPosRoute
  '/_authenticated/cafe/$slug/reports': typeof AuthenticatedCafeSlugReportsRoute
  '/_authenticated/cafe/$slug/staff': typeof AuthenticatedCafeSlugStaffRoute
  '/_authenticated/cafe/$slug/support': typeof AuthenticatedCafeSlugSupportRoute
  '/_authenticated/cafe/$slug/tournaments': typeof AuthenticatedCafeSlugTournamentsRouteWithChildren
  '/_authenticated/cafe/$slug/wallet': typeof AuthenticatedCafeSlugWalletRoute
  '/c/$slug/tournaments/$id': typeof CSlugTournamentsIdRoute
  '/_authenticated/cafe/$slug/': typeof AuthenticatedCafeSlugIndexRoute
  '/_authenticated/cafe/$slug/tournaments/$id': typeof AuthenticatedCafeSlugTournamentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/discover'
    | '/login'
    | '/redirecting'
    | '/reset-password'
    | '/setup'
    | '/signup'
    | '/admin'
    | '/owner'
    | '/portal'
    | '/c/$slug'
    | '/admin/announcements'
    | '/admin/api-keys'
    | '/admin/audit'
    | '/admin/backups'
    | '/admin/cafes'
    | '/admin/config'
    | '/admin/health'
    | '/admin/leads'
    | '/admin/reports'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/users'
    | '/cafe/$slug'
    | '/owner/help'
    | '/admin/'
    | '/cafe/$slug/analytics'
    | '/cafe/$slug/audit'
    | '/cafe/$slug/bookings'
    | '/cafe/$slug/customers'
    | '/cafe/$slug/devices'
    | '/cafe/$slug/floor'
    | '/cafe/$slug/ledger'
    | '/cafe/$slug/memberships'
    | '/cafe/$slug/menu'
    | '/cafe/$slug/page'
    | '/cafe/$slug/pos'
    | '/cafe/$slug/reports'
    | '/cafe/$slug/staff'
    | '/cafe/$slug/support'
    | '/cafe/$slug/tournaments'
    | '/cafe/$slug/wallet'
    | '/c/$slug/tournaments/$id'
    | '/cafe/$slug/'
    | '/cafe/$slug/tournaments/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/discover'
    | '/login'
    | '/redirecting'
    | '/reset-password'
    | '/setup'
    | '/signup'
    | '/owner'
    | '/portal'
    | '/c/$slug'
    | '/admin/announcements'
    | '/admin/api-keys'
    | '/admin/audit'
    | '/admin/backups'
    | '/admin/cafes'
    | '/admin/config'
    | '/admin/health'
    | '/admin/leads'
    | '/admin/reports'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/users'
    | '/owner/help'
    | '/admin'
    | '/cafe/$slug/analytics'
    | '/cafe/$slug/audit'
    | '/cafe/$slug/bookings'
    | '/cafe/$slug/customers'
    | '/cafe/$slug/devices'
    | '/cafe/$slug/floor'
    | '/cafe/$slug/ledger'
    | '/cafe/$slug/memberships'
    | '/cafe/$slug/menu'
    | '/cafe/$slug/page'
    | '/cafe/$slug/pos'
    | '/cafe/$slug/reports'
    | '/cafe/$slug/staff'
    | '/cafe/$slug/support'
    | '/cafe/$slug/tournaments'
    | '/cafe/$slug/wallet'
    | '/c/$slug/tournaments/$id'
    | '/cafe/$slug'
    | '/cafe/$slug/tournaments/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/discover'
    | '/login'
    | '/redirecting'
    | '/reset-password'
    | '/setup'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/owner'
    | '/_authenticated/portal'
    | '/c/$slug'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/api-keys'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/backups'
    | '/_authenticated/admin/cafes'
    | '/_authenticated/admin/config'
    | '/_authenticated/admin/health'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/revenue'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/cafe/$slug'
    | '/_authenticated/owner_/help'
    | '/_authenticated/admin/'
    | '/_authenticated/cafe/$slug/analytics'
    | '/_authenticated/cafe/$slug/audit'
    | '/_authenticated/cafe/$slug/bookings'
    | '/_authenticated/cafe/$slug/customers'
    | '/_authenticated/cafe/$slug/devices'
    | '/_authenticated/cafe/$slug/floor'
    | '/_authenticated/cafe/$slug/ledger'
    | '/_authenticated/cafe/$slug/memberships'
    | '/_authenticated/cafe/$slug/menu'
    | '/_authenticated/cafe/$slug/page'
    | '/_authenticated/cafe/$slug/pos'
    | '/_authenticated/cafe/$slug/reports'
    | '/_authenticated/cafe/$slug/staff'
    | '/_authenticated/cafe/$slug/support'
    | '/_authenticated/cafe/$slug/tournaments'
    | '/_authenticated/cafe/$slug/wallet'
    | '/c/$slug/tournaments/$id'
    | '/_authenticated/cafe/$slug/'
    | '/_authenticated/cafe/$slug/tournaments/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DiscoverRoute: typeof DiscoverRoute
  LoginRoute: typeof LoginRoute
  RedirectingRoute: typeof RedirectingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  SignupRoute: typeof SignupRoute
  CSlugRoute: typeof CSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirecting': {
      id: '/redirecting'
      path: '/redirecting'
      fullPath: '/redirecting'
      preLoaderRoute: typeof RedirectingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner': {
      id: '/_authenticated/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AuthenticatedOwnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/owner_/help': {
      id: '/_authenticated/owner_/help'
      path: '/owner/help'
      fullPath: '/owner/help'
      preLoaderRoute: typeof AuthenticatedOwnerHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cafe/$slug': {
      id: '/_authenticated/cafe/$slug'
      path: '/cafe/$slug'
      fullPath: '/cafe/$slug'
      preLoaderRoute: typeof AuthenticatedCafeSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/revenue': {
      id: '/_authenticated/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AuthenticatedAdminRevenueRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/health': {
      id: '/_authenticated/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AuthenticatedAdminHealthRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/config': {
      id: '/_authenticated/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AuthenticatedAdminConfigRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cafes': {
      id: '/_authenticated/admin/cafes'
      path: '/cafes'
      fullPath: '/admin/cafes'
      preLoaderRoute: typeof AuthenticatedAdminCafesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/backups': {
      id: '/_authenticated/admin/backups'
      path: '/backups'
      fullPath: '/admin/backups'
      preLoaderRoute: typeof AuthenticatedAdminBackupsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/api-keys': {
      id: '/_authenticated/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AuthenticatedAdminApiKeysRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/cafe/$slug/': {
      id: '/_authenticated/cafe/$slug/'
      path: '/'
      fullPath: '/cafe/$slug/'
      preLoaderRoute: typeof AuthenticatedCafeSlugIndexRouteImport
      parentRoute: typeof AuthenticatedCafeSlugRoute
    }
    '/c/$slug/tournaments/$id': {
      id: '/c/$slug/tournaments/$id'
      path: '/tournaments/$id'
      fullPath: '/c/$slug/tournaments/$id'
      preLoaderRoute: typeof CSlugTournamentsIdRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/_authenticated/cafe/$slug/wallet': {
      id: '/_authenticated/cafe/$slug/wallet'
      path: '/wallet'
      fullPath: '/cafe/$slug/wallet'
      preLoaderRoute: typeof AuthenticatedCafeSlugWalletRouteImport
      parentRoute: typeof AuthenticatedCafeSlugRoute
    }
    '/_authenticated/cafe/$slug/tournaments': {
      id: '/_authenticated/cafe/$slug/tournaments'
      path: '/tournaments'
      fullPath: '/cafe/$slug/tournaments'
      preLoaderRoute: typeof AuthenticatedCafeSlugTournamentsRouteImport
      parentRoute: typeof AuthenticatedCafeSlugRoute
    }
    '/_authenticated/cafe/$slug/support': {
      id: '/_authenticated/cafe/$slug/support'
      path: '/support'
      fullPath: '/cafe/$slug/support'
      preLoaderRoute: typeof AuthenticatedCafeSlugSupportRouteImport
      parentRoute: typeof AuthenticatedCafeSlugRoute
    }
    '/_authenticated/cafe/$slug/staff': {
      id: '/_authenticated/cafe/$slug/staff'
      path: '/staff'
      fullPath: '/cafe/$slug/staff'
      preLoaderRoute: typeof AuthenticatedCafeSlugStaffRouteImport
      parentRoute: typeof AuthenticatedCafeSlugRoute
    }
    '/_authenticated/cafe/$slug/reports': {
      id: '/_authenticated/cafe/$slug/reports'
      path: '/reports'
      fullPath: '/cafe/$slug/reports'
      preLoaderRoute: typeof AuthenticatedCafeSlugReportsRouteImport
      parentRoute: typeof AuthenticatedCafeSlugRoute
    }
    '/_authenticated/cafe/$slug/pos': {
      id: '/_authenticated/cafe/$slug/pos'
      path: '/pos'
      fullPath: '/cafe/$slug/pos'
      preLoaderRoute: typeof AuthenticatedCafeSlugPosRouteImport
      parentRoute: typeof AuthenticatedCafeSlugRoute
    }
    '/_authenticated/cafe/$slug/page': {
      id: '/_authenticated/cafe/$slug/page'
      path: '/page'
      fullPath: '/cafe/$slug/page'
      preLoaderRoute: typeof AuthenticatedCafeSlugPageRouteImport
      parentRoute: typeof AuthenticatedCafeSlugRoute
    }
    '/_authenticated/cafe/$slug/menu': {
      id: '/_authenticated/cafe/$slug/menu'
      path: '/menu'
      fullPath: '/cafe/$slug/menu'
      preLoaderRoute: typeof AuthenticatedCafeSlugMenuRouteImport
      parentRoute: typeof AuthenticatedCafeSlugRoute
    }
    '/_authenticated/cafe/$slug/memberships': {
      id: '/_authenticated/cafe/$slug/memberships'
      path: '/memberships'
      fullPath: '/cafe/$slug/memberships'
      preLoaderRoute: typeof AuthenticatedCafeSlugMembershipsRouteImport
      parentRoute: typeof AuthenticatedCafeSlugRoute
    }
    '/_authenticated/cafe/$slug/ledger': {
      id: '/_authenticated/cafe/$slug/ledger'
      path: '/ledger'
      fullPath: '/cafe/$slug/ledger'
      preLoaderRoute: typeof AuthenticatedCafeSlugLedgerRouteImport
      parentRoute: typeof AuthenticatedCafeSlugRoute
    }
    '/_authenticated/cafe/$slug/floor': {
      id: '/_authenticated/cafe/$slug/floor'
      path: '/floor'
      fullPath: '/cafe/$slug/floor'
      preLoaderRoute: typeof AuthenticatedCafeSlugFloorRouteImport
      parentRoute: typeof AuthenticatedCafeSlugRoute
    }
    '/_authenticated/cafe/$slug/devices': {
      id: '/_authenticated/cafe/$slug/devices'
      path: '/devices'
      fullPath: '/cafe/$slug/devices'
      preLoaderRoute: typeof AuthenticatedCafeSlugDevicesRouteImport
      parentRoute: typeof AuthenticatedCafeSlugRoute
    }
    '/_authenticated/cafe/$slug/customers': {
      id: '/_authenticated/cafe/$slug/customers'
      path: '/customers'
      fullPath: '/cafe/$slug/customers'
      preLoaderRoute: typeof AuthenticatedCafeSlugCustomersRouteImport
      parentRoute: typeof AuthenticatedCafeSlugRoute
    }
    '/_authenticated/cafe/$slug/bookings': {
      id: '/_authenticated/cafe/$slug/bookings'
      path: '/bookings'
      fullPath: '/cafe/$slug/bookings'
      preLoaderRoute: typeof AuthenticatedCafeSlugBookingsRouteImport
      parentRoute: typeof AuthenticatedCafeSlugRoute
    }
    '/_authenticated/cafe/$slug/audit': {
      id: '/_authenticated/cafe/$slug/audit'
      path: '/audit'
      fullPath: '/cafe/$slug/audit'
      preLoaderRoute: typeof AuthenticatedCafeSlugAuditRouteImport
      parentRoute: typeof AuthenticatedCafeSlugRoute
    }
    '/_authenticated/cafe/$slug/analytics': {
      id: '/_authenticated/cafe/$slug/analytics'
      path: '/analytics'
      fullPath: '/cafe/$slug/analytics'
      preLoaderRoute: typeof AuthenticatedCafeSlugAnalyticsRouteImport
      parentRoute: typeof AuthenticatedCafeSlugRoute
    }
    '/_authenticated/cafe/$slug/tournaments/$id': {
      id: '/_authenticated/cafe/$slug/tournaments/$id'
      path: '/$id'
      fullPath: '/cafe/$slug/tournaments/$id'
      preLoaderRoute: typeof AuthenticatedCafeSlugTournamentsIdRouteImport
      parentRoute: typeof AuthenticatedCafeSlugTournamentsRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminApiKeysRoute: typeof AuthenticatedAdminApiKeysRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBackupsRoute: typeof AuthenticatedAdminBackupsRoute
  AuthenticatedAdminCafesRoute: typeof AuthenticatedAdminCafesRoute
  AuthenticatedAdminConfigRoute: typeof AuthenticatedAdminConfigRoute
  AuthenticatedAdminHealthRoute: typeof AuthenticatedAdminHealthRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminRevenueRoute: typeof AuthenticatedAdminRevenueRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminApiKeysRoute: AuthenticatedAdminApiKeysRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminBackupsRoute: AuthenticatedAdminBackupsRoute,
  AuthenticatedAdminCafesRoute: AuthenticatedAdminCafesRoute,
  AuthenticatedAdminConfigRoute: AuthenticatedAdminConfigRoute,
  AuthenticatedAdminHealthRoute: AuthenticatedAdminHealthRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminRevenueRoute: AuthenticatedAdminRevenueRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedCafeSlugTournamentsRouteChildren {
  AuthenticatedCafeSlugTournamentsIdRoute: typeof AuthenticatedCafeSlugTournamentsIdRoute
}

const AuthenticatedCafeSlugTournamentsRouteChildren: AuthenticatedCafeSlugTournamentsRouteChildren =
  {
    AuthenticatedCafeSlugTournamentsIdRoute:
      AuthenticatedCafeSlugTournamentsIdRoute,
  }

const AuthenticatedCafeSlugTournamentsRouteWithChildren =
  AuthenticatedCafeSlugTournamentsRoute._addFileChildren(
    AuthenticatedCafeSlugTournamentsRouteChildren,
  )

interface AuthenticatedCafeSlugRouteChildren {
  AuthenticatedCafeSlugAnalyticsRoute: typeof AuthenticatedCafeSlugAnalyticsRoute
  AuthenticatedCafeSlugAuditRoute: typeof AuthenticatedCafeSlugAuditRoute
  AuthenticatedCafeSlugBookingsRoute: typeof AuthenticatedCafeSlugBookingsRoute
  AuthenticatedCafeSlugCustomersRoute: typeof AuthenticatedCafeSlugCustomersRoute
  AuthenticatedCafeSlugDevicesRoute: typeof AuthenticatedCafeSlugDevicesRoute
  AuthenticatedCafeSlugFloorRoute: typeof AuthenticatedCafeSlugFloorRoute
  AuthenticatedCafeSlugLedgerRoute: typeof AuthenticatedCafeSlugLedgerRoute
  AuthenticatedCafeSlugMembershipsRoute: typeof AuthenticatedCafeSlugMembershipsRoute
  AuthenticatedCafeSlugMenuRoute: typeof AuthenticatedCafeSlugMenuRoute
  AuthenticatedCafeSlugPageRoute: typeof AuthenticatedCafeSlugPageRoute
  AuthenticatedCafeSlugPosRoute: typeof AuthenticatedCafeSlugPosRoute
  AuthenticatedCafeSlugReportsRoute: typeof AuthenticatedCafeSlugReportsRoute
  AuthenticatedCafeSlugStaffRoute: typeof AuthenticatedCafeSlugStaffRoute
  AuthenticatedCafeSlugSupportRoute: typeof AuthenticatedCafeSlugSupportRoute
  AuthenticatedCafeSlugTournamentsRoute: typeof AuthenticatedCafeSlugTournamentsRouteWithChildren
  AuthenticatedCafeSlugWalletRoute: typeof AuthenticatedCafeSlugWalletRoute
  AuthenticatedCafeSlugIndexRoute: typeof AuthenticatedCafeSlugIndexRoute
}

const AuthenticatedCafeSlugRouteChildren: AuthenticatedCafeSlugRouteChildren = {
  AuthenticatedCafeSlugAnalyticsRoute: AuthenticatedCafeSlugAnalyticsRoute,
  AuthenticatedCafeSlugAuditRoute: AuthenticatedCafeSlugAuditRoute,
  AuthenticatedCafeSlugBookingsRoute: AuthenticatedCafeSlugBookingsRoute,
  AuthenticatedCafeSlugCustomersRoute: AuthenticatedCafeSlugCustomersRoute,
  AuthenticatedCafeSlugDevicesRoute: AuthenticatedCafeSlugDevicesRoute,
  AuthenticatedCafeSlugFloorRoute: AuthenticatedCafeSlugFloorRoute,
  AuthenticatedCafeSlugLedgerRoute: AuthenticatedCafeSlugLedgerRoute,
  AuthenticatedCafeSlugMembershipsRoute: AuthenticatedCafeSlugMembershipsRoute,
  AuthenticatedCafeSlugMenuRoute: AuthenticatedCafeSlugMenuRoute,
  AuthenticatedCafeSlugPageRoute: AuthenticatedCafeSlugPageRoute,
  AuthenticatedCafeSlugPosRoute: AuthenticatedCafeSlugPosRoute,
  AuthenticatedCafeSlugReportsRoute: AuthenticatedCafeSlugReportsRoute,
  AuthenticatedCafeSlugStaffRoute: AuthenticatedCafeSlugStaffRoute,
  AuthenticatedCafeSlugSupportRoute: AuthenticatedCafeSlugSupportRoute,
  AuthenticatedCafeSlugTournamentsRoute:
    AuthenticatedCafeSlugTournamentsRouteWithChildren,
  AuthenticatedCafeSlugWalletRoute: AuthenticatedCafeSlugWalletRoute,
  AuthenticatedCafeSlugIndexRoute: AuthenticatedCafeSlugIndexRoute,
}

const AuthenticatedCafeSlugRouteWithChildren =
  AuthenticatedCafeSlugRoute._addFileChildren(
    AuthenticatedCafeSlugRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedOwnerRoute: typeof AuthenticatedOwnerRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedCafeSlugRoute: typeof AuthenticatedCafeSlugRouteWithChildren
  AuthenticatedOwnerHelpRoute: typeof AuthenticatedOwnerHelpRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedOwnerRoute: AuthenticatedOwnerRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedCafeSlugRoute: AuthenticatedCafeSlugRouteWithChildren,
  AuthenticatedOwnerHelpRoute: AuthenticatedOwnerHelpRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CSlugRouteChildren {
  CSlugTournamentsIdRoute: typeof CSlugTournamentsIdRoute
}

const CSlugRouteChildren: CSlugRouteChildren = {
  CSlugTournamentsIdRoute: CSlugTournamentsIdRoute,
}

const CSlugRouteWithChildren = CSlugRoute._addFileChildren(CSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DiscoverRoute: DiscoverRoute,
  LoginRoute: LoginRoute,
  RedirectingRoute: RedirectingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  SignupRoute: SignupRoute,
  CSlugRoute: CSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
